name = "Hasamap"
license = "MIT"
licenselink = "https://github.com/jwerts/hugo-theme-hasamap/blob/master/LICENSE.md"
description = "Steam + a map and personal changes"
homepage = ""
tags = ["google analytics", "google glus", "disqus", "ghost", "blog", "minimal", "custom themes", "single column"]
features = ["", ""]
min_version = 0.14

# Many changes to Steam for custom theme.
[author]
  name = "Josh Werts"
  homepage = "//github.com/jwerts"

# Author who ported steam theme to Hugo
[[original]]
  name = "Digitalcraftsman"
  homepage = "//github.com/digitalcraftsman/"

# Author who used the Vapor theme as foundation for Steam
[[original]]
  name = "Tommaso Barbato"
  homepage = "//torb.at/"
  repo = "//github.com/epistrephein/Steam"

# Original creator of the Vapor theme
[[original]]
  name = "Seth Lilly"
  homepage = "//www.sethlilly.com/"
  repo = "//github.com/sethlilly/Vapor"
